name: arduino cli

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2
      - name: install board for BG770A
        run: |
          arduino-cli config add board_manager.additional_urls 'https://www.seeed.co.jp/package_SeeedJP_index.json'
          arduino-cli core search
          arduino-cli core install SeeedJP:nrf52
          arduino-cli board list
      - name: build blink.ino
        run: |
          arduino-cli compile --fqbn SeeedJP:nrf52:wio_bg770a blink
